services:
  
  prometheus:
    image: prom/prometheus:v2.47.1
    volumes:
      - ./Configs/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana:10.1.4
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./Configs/grafana.ini:/etc/grafana/grafana.ini
      - ./Configs/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./Configs/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./Configs/dotnet-otel-dashboard.json:/etc/grafana/provisioning/dashboards/dotnet-otel-dashboard.json
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - backend
  
  metricsplayground:
    image: metricsplayground
    build:
      context: .
      dockerfile: MetricsPlayground/Dockerfile
    networks:
      - backend
    ports:
      - "127.0.0.1:8050:8050"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8050

networks:
  backend: