{
 "title": "TelemetryMetrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service_name", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total calls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "calls_total{service_name=\"$service_name\"}"
    }
   ]
  },
  {
   "title": "Order items added",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OrderItemsAdded_total{instance=\"order-service:8050\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total orders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "OrderAdded_total{instance=\"order-service:8050\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "UserAdded_total{instance=\"user-service:8060\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}