{
 "title": "Logs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service",
    "query": {}
   },
   {
    "name": "level",
    "label": "Level",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ERROR Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({level=\"ERROR\", service_name=\"$service_name\"} [$__range])"
    }
   ]
  },
  {
   "title": "INFO Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({level=\"INFO\", service_name=\"$service_name\"} [$__range])"
    }
   ]
  },
  {
   "title": "WARN Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({level=\"WARN\", service_name=\"$service_name\"} [$__range])"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 33, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{service_name=\"$service_name\"} | json | level =~ `$level` | line_format `[{{ .level }}] {{ .body }}`"
    }
   ]
  }
 ]
}