global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: services
    static_configs:
      - targets:
          - api-gateway:8090
          - validation-service:8070
          - user-service:8060
          - order-service:8050
