services:
  
  seq:
    image: datalust/seq:latest
    ports:
      - '8033:80'
      - '5341:5341'
    environment:
      ACCEPT_EULA: Y
  
  api:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8040:8040"
    volumes:
      - ../Logs:/app/Logs
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8040
      - SERVICE_COUNT=3
  
  anotherservice1:
    image: anotherservice
    build:
      context: .
      dockerfile: AnotherService/Dockerfile
    ports:
      - "8041:8041"
    volumes:
      - ../Logs:/app/Logs
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8041
      - SERVICE_NAME=AnotherService1
      - TimerIntervalMs=3000
  
  
  anotherservice2:
    image: anotherservice
    build:
      context: .
      dockerfile: AnotherService/Dockerfile
    ports:
      - "8042:8041"
    volumes:
      - ../Logs:/app/Logs
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8041
      - SERVICE_NAME=AnotherService2
      - TimerIntervalMs=4000
  
  anotherservice3:
    image: anotherservice
    build:
      context: .
      dockerfile: AnotherService/Dockerfile
    ports:
      - "8043:8041"
    volumes:
      - ../Logs:/app/Logs
    depends_on:
      - api
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8041
      - SERVICE_NAME=AnotherService3
      - TimerIntervalMs=5000

networks:
  backend: