{
 "title": "Logs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "AnotherService2",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"AnotherService2\"} |= ``"
    }
   ]
  },
  {
   "title": "AnotherService1",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"AnotherService1\"} |= ``"
    }
   ]
  },
  {
   "title": "Api gateway",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"ApiGateway\"} |= ``"
    }
   ]
  }
 ]
}