global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: services
    static_configs:
      - targets:
          - OpenTelemetryPlayground:5000
